#!/usr/bin/env -S bash -u

# 引数を渡すとセッション名として解釈してtmuxのセッションにアタッチします
# 引数が何も無いとfzfを起動して、その結果をセッション名と解釈します
# CTRL-Nを押すと入力しているクエリをそのまま使います(新しいセッションを立ち上げるのを想定)
# セッション名があればアタッチし、無ければセッションを作成します

: ${DISPLAY:=:0}
export DISPLAY

if [[ $# = 0 ]]; then
  SESSION=$(tmux ls -F "#{session_last_attached}	#S" | sort -nr | cut -f2 | fzf +s \
    --bind "ctrl-n:print-query")
  if [[ "$?" != 0 ]]; then
    exit 1
  fi
  echo $SESSION
  if [[ "$SESSION" = "" ]]; then
    SESSION=default
  fi
else
  SESSION=$1
fi

tmux new-session -d -s $SESSION 2> /dev/null
if [[ "${TMUX:-}" == "" ]]; then
  # tmux detach-session -s $SESSION
  TERM=xterm-256color exec tmux attach-session -d -t $SESSION
else
  tmux switch-client -t $SESSION
fi
