#!/bin/sh -u
rm -rf /tmp/nix
git clone . /tmp/nix
if command -v nom > /dev/null; then
  function build () {
    nix build -j 0 "$@"
    nom build "$@"
  }
else
  function build() {
    nix build "$@"
  }
fi
(
  cd /tmp/nix
  build -L -o /data/nix/result-git
)
[[ $? == 0 ]] || exit 1
(
  cd /tmp/nix
  # nix run '.#home-manager' -- -L --arg -b nixspill --flake . build
  build -L -o /data/nix/result-git-hm ".#homeConfigurations.\"${1:-$(id -nu)}\".activationPackage"
)
