#!/bin/sh -u
rm -rf /tmp/nix
git clone . /tmp/nix
if ! command -v nom > /dev/null; then
  alias nom=nix
fi
(
  set -e
  cd /tmp/nix
  nom build -L -o /data/nix/result-git
)
(
  set -e
  cd /tmp/nix
  # nix run '.#home-manager' -- -L --arg -b nixspill --flake . build
  nom build -L -o /data/nix/result-git-hm ".#homeConfigurations.\"${1:-$(id -nu)}\".activationPackage"
)
