#!/usr/bin/env -S bash -u
rm -rf /tmp/nix
git clone . /tmp/nix
(
  set -e
  cd /tmp/nix
  nix build -L -o /data/nix/result-git
  # cd -
  # rm -rf result-git
  # cp -a /tmp/nix/result result-git
)
(
  set -e
  cd /tmp/nix
  # t/hb
  # nix run '.#home-manager' -- -L --arg -b nixspill --flake . build
  nix build -L -o /data/nix/result-git-hm ".#homeConfigurations.\"${1:-$(id -nu)}\".activationPackage"
)
