#!/bin/sh

cd $(git rev-parse --show-toplevel)
if git log --oneline | head -n1 | grep -q 'あぷでたん'; then
  git reset HEAD^
fi
git restore flake.lock

remote_head=$(git ls-remote --heads https://github.com/NixOS/nixpkgs nixos-unstable | awk '{print $1}')
local_head=$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock)
echo $remote_head
echo $local_head
if [[ "$remote_head" = "$local_head" ]]; then
  nix flake update
  git add flake.lock
  git commit -m あぷでたん
else
  nix flake update --commit-lock-file
fi
